accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup_view, name="signup"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
]

articles/urls.py
from django.urls import path, re_path
from . import views


#  Namespace the app so that you can reference specific list and details in your template
app_name = "articles"

# URLConf
urlpatterns = [
    path("hello/", views.say_hello, name="hello"),
    re_path(r"^$", views.article_list, name="list"),
    path("create/", views.article_create, name="create"),  # Named Capturing Group
    # Here we capture the variable slug and send it through to the view:
    path(
        "<slug:my_slug>/", views.article_detail, name="detail"
    ),  # Named Capturing Group
]

resolve/urls.py
from django.urls import path
from . import views


#  Namespace the app so that you can reference specific list and details in your template
app_name = "resolve"

# URLConf
urlpatterns = [
    path("resolve", views.resolve_main, name="resolve"),
    path("unused", views.resolve_unused, name="unused"),
    # Here we capture the variable slug and send it through to the view:
    # path(
    #     "<slug:my_slug>/", views.article_detail, name="detail"
    # ),  # Named Capturing Group
]

storefront/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include(debug_toolbar.urls)),
    path("", include("resolve.urls")),
]

urlpatterns += staticfiles_urlpatterns()

articles/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()  # URL friendly string
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + "..."

resolve/models.py
from django.db import models

# Create your models here.

articles/forms.py
from django import forms

from . import models


class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ["title", "body", "slug"]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages


def signup_view(request):
    # First check if request is POST
    if request.method == "POST":
        # By passing the data back to a new instance of the form we
        # are validating the data
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Registration successful. You can now log in.")
            return redirect("accounts:login")  # Redirect to the login page
    else:
        # If it's a GET request then go to the forms
        form = UserCreationForm()
    # This will still run if the if fails
    return render(request, "accounts/signup.html", {"form": form})


def login_view(request):
    if request.method == "POST":
        # Get the username and password from the submitted form
        username = request.POST["username"]
        password = request.POST["password"]

        # Authenticate the user
        user = authenticate(request, username=username, password=password)

        if user is not None:
            # Log the user in
            login(request, user)
            messages.success(request, "Login successful.")

            if "next" in request.POST:
                return redirect(request.POST.get("next"))
            else:
                return redirect("articles:list")
        else:
            messages.error(request, "Invalid username or password.")

    # If the request method is GET or authentication failed, display login form
    form = AuthenticationForm()
    return render(request, "accounts/login.html", {"form": form})


def logout_view(request):
    if request.method == "POST":
        # Use the logout() function to log the user out
        logout(request)
    return redirect(
        "articles:list"
    )  # Redirect to the home page or any desired page after logout

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.contrib.auth.decorators import login_required
from . import forms


# In Django views are request handlers or Actions
def say_hello(request):
    return render(request, template_name="hello.html", context={"name": "Alex"})


def article_list(request):
    articles = Article.objects.all().order_by("date")
    return render(
        request,
        template_name="articles/article_list.html",
        context={"articles": articles},
    )


def article_detail(request, my_slug):
    article = Article.objects.get(slug=my_slug)
    # return HttpResponse(article.body)
    return render(request, "articles/article_detail.html", context={"article": article})


@login_required(login_url="/accounts/login/")  # This decorator protects this view
def article_create(request):
    if request.method == "POST":
        form = forms.CreateArticle(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            # Attach author to instance of article
            instance.author = request.user
            instance.save()
            return redirect("articles:list")
    else:
        form = forms.CreateArticle()
    return render(request, "articles/article_create.html", context={"form": form})

resolve/views.py
from django.http import HttpResponse
from django.shortcuts import render


def manipulate_input(input_text):
    # Perform your manipulation logic here
    # For example, you can convert the input to uppercase
    return input_text.upper()


def resolve_main(request):
    user_input = ""
    output = ""

    if request.method == "POST":
        user_input = request.POST.get("user_input", "")  # Retrieve the user's input

        # Manipulate the user input before displaying it
        output = manipulate_input(user_input)

    return render(
        request,
        "resolve_views/resolve.html",
        {"user_input": user_input, "output": output},
    )


def resolve_unused(request):
    response_string = "Hello, this is a simple HttpResponse string!"
    return HttpResponse(response_string)

storefront/views.py
from django.shortcuts import render


def homepage(request):
    return render(request, "homepage.html")


def about(request):
    return render(request, "about.html")

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Login</h1>
<form class="site-form" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
    <input type="hidden" , name="next" , value="{{request.GET.next}}">
    {% endif %}
    <input type="submit" value="Login">
</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Signup</h1>
<form class="site-form" action="{% url 'accounts:signup' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Signup">
</form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-create">
    <h2>Create a new article</h2>
    <form class="site-form" action="{% url 'articles:create' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Create">
    </form>
</div>
<script src="/static/slugify.js"></script>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
    <div class="aricle">
        <h2> {{article.title}} </h2>
            <p> {{ article.body }} </p>
            <p> {{ article.date }} </p>
    </div>
</div>
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
  <h1>Article List</h1>

  <div class="container-lg my-5">

    <div class="row">
    {% for article in articles %}

    <div class="col">
      <div class="card bg-dark text-white" style="width: 18rem;">
        <div class="card-body">
          <h2><a href="{% url 'articles:detail' my_slug=article.slug %}">{{ article.title }}</a></h2>
          <p>{{ article.snippet }}</p>
          <p>{{ article.date }}</p>
          <p class="author">Added by {{ article.author.username }}</p>
        </div>
      </div>
    </div>
      
    {% endfor %}
    </div>

  </div>
{% endblock %}

articles/templates/base_layout.html
{% load static %}

<html>
  <head>
    <meta charset="utf-8" />
    <title>Articles</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}" />
  </head>

  <body>
    <header class="wrapper">
      <h1><a href="{% url 'home' %}"><img src="{% static 'logo.png' %}" /></a></h1>
      <nav>
        <ul>
          {% csrf_token %}
          {% if user.is_authenticated %}
            <li>
              <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">Logout</button>
              </form>
            </li>
            <li>
              <a href="{% url 'articles:create' %}" class="highlight">New Article</a>
            </li>
          {% else %}
            <li>
              <a href="{% url 'accounts:login' %}">Login</a>
            </li>
            <li>
              <a href="{% url 'accounts:signup' %}">Signup</a>
            </li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <div class="wrapper">
      {% block content %}

      {% endblock %}
    </div>
  </body>
</html>

articles/templates/base_layout2.html
{% load static %}

<html>
  <head>
    <meta charset="utf-8" />
    <title>Articles</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles.css' %}" />
  </head>

  <body>
    <header class="wrapper">
      <h1><a href="{% url 'home' %}"><img src="{% static 'logo.png' %}" /></a></h1>
      <nav>
        <ul>
          {% csrf_token %}
          {% if user.is_authenticated %}
            <li>
              <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">Logout</button>
              </form>
            </li>
            <li>
              <a href="{% url 'articles:create' %}" class="highlight">New Article</a>
            </li>
          {% else %}
            <li>
              <a href="{% url 'accounts:login' %}">Login</a>
            </li>
            <li>
              <a href="{% url 'accounts:signup' %}">Signup</a>
            </li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <div class="wrapper">
      {% block content %}

      {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

articles/templates/hello.html
<html>
  <body>
    {% if name %}
      <h1>Hello {{ name }}</h1>
    {% else %}
      <h1>Hello World</h1>
    {% endif %}
  </body>
</html>

resolve/templates/base_layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
  <body>
    <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasExampleLabel">Offcanvas</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <div>Some text as placeholder. In real life you can have the elements you have chosen. Like, text, images, lists, etc.</div>
        <div class="dropdown mt-3">
          <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown">Dropdown button</button>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" href="#">Action</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Another action</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Something else here</a>
            </li>
          </ul>
        </div>
      </div>
    </div>

	<!-- Nav Bar -->

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
		<a class="btn" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
			<i class="bi-list"></i> <!-- Bootstrap Icon for the hamburger icon -->
		</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'resolve:unused' %}">Home</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
              <ul class="dropdown-menu">
                <li>
                  <a class="dropdown-item" href="#">Action</a>
                </li>
                <li>
                  <a class="dropdown-item" href="#">Another action</a>
                </li>
                <li>
                  <hr class="dropdown-divider" />
                </li>
                <li>
                  <a class="dropdown-item" href="#">Something else here</a>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>

	<!-- Main page content -->

    <div class="wrapper">
      {% block content %}

      {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

resolve/templates/resolve_views/resolve.html
{% extends 'base_layout.html' %}

{% block content %}
  <div class="container my-5" style="height: 100vh;">
    <div class="row justify-content-center align-items-top">
      <h3>Welcome to my tool!</h3>

      <!-- First Column -->
      <div class="col-md-6 my-2">
        <div class="form-group">
          <form method="post">
            {% csrf_token %}

            <h5 for="inputField1">Input:</h5>
            <input type="text" class="form-control" id="inputField1" name="user_input" placeholder="Enter something..." value="{{ user_input }}" />
            <br />
            <input type="submit" value="Submit" />
          </form>
        </div>
      </div>

      <!-- Second Column -->
      <div class="col-md-6 my-2">
        <div class="form-group">
          <div class="card-body">
            <h5 class="card-title">Output:</h5>
            <p class="card-text" id="output-text"></p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script>
    // JavaScript code to stream output letter by letter
    var outputText = document.getElementById("output-text");
    var outputContent = "{{ output }}"; // Content to be streamed

    function streamOutput() {
      var i = 0;
      var interval = setInterval(function() {
        if (i < outputContent.length) {
          outputText.innerHTML += outputContent.charAt(i);
          i++;
        } else {
          clearInterval(interval); // Stop streaming when done
        }
      }, 100); // Adjust the interval as needed for the desired speed
    }

    // Call the streamOutput function when the page loads
    window.addEventListener("load", streamOutput);
  </script>

{% endblock %}